export const REQUEST_CREATE_GROUP = 'REQUEST_CREATE_GROUP';
export const SUCCESS_CREATE_GROUP = 'SUCCESS_CREATE_GROUP';
export const ERROR_CREATE_GROUP = 'ERROR_CREATE_GROUP';

export const REQUEST_GET_ALL_GROUPS = 'REQUEST_GET_ALL_GROUPS';
export const SUCCESS_ALL_GROUPS = 'SUCCESS_ALL_GROUPS';
export const ERROR_ALL_GROUPS = 'ERROR_ALL_GROUPS';
