export const LOG_IN_API_REQUEST = 'LOG_IN_API_REQUEST';
export const LOG_IN_API_SUCCEEDED = 'LOG_IN_API_SUCCEEDED';
export const LOG_IN_API_GET_TOKEN_SUCCEEDED = 'LOG_IN_API_GET_TOKEN_SUCCEEDED';
export const LOG_IN_API_FAILED = 'LOG_IN_API_FAILED';

export const LOG_OUT = 'LOG_OUT';

export const OPEN_WINDOW_AUTH = 'OPEN_WINDOW_AUTH';
export const CLOSE_WINDOW_AUTH = 'CLOSE_WINDOW_AUTH';

export const RESET_ERROR = 'RESET_ERROR';

export const CREATE_USER_DATE_IN_API_REQUEST = 'CREATE_USER_DATE_IN_API_REQUEST';
export const CREATE_USER_DATE_IN_API_SUCCEEDED = 'CREATE_USER_DATE_IN_API_SUCCEEDED';
export const CREATE_USER_DATE_IN_API_GET_TOKEN_SUCCEEDED =
  'CREATE_USER_DATE_IN_API_GET_TOKEN_SUCCEEDED';
export const CREATE_USER_DATE_IN_API_FAILED = 'CREATE_USER_DATE_IN_API_FAILED';

export const CREATE_USER_BY_TELEGRAM_IN_API_REQUEST = 'CREATE_USER_BY_TELEGRAM_IN_API_REQUEST';
export const CREATE_USER_BY_TELEGRAM_IN_API_SUCCEEDED = 'CREATE_USER_BY_TELEGRAM_IN_API_SUCCEEDED';
export const CREATE_USER_BY_TELEGRAM_IN_API_GET_TOKEN_SUCCEEDED =
  'CREATE_USER_BY_TELEGRAM_IN_API_GET_TOKEN_SUCCEEDED';
export const CREATE_USER_BY_TELEGRAM_IN_API_FAILED = 'CREATE_USER_BY_TELEGRAM_IN_API_FAILED';

export const EDIT_USER_DATE_IN_API_REQUEST = 'EDIT_USER_DATE_IN_API_REQUEST';
export const EDIT_USER_DATE_IN_API_SUCCEEDED = 'EDIT_USER_DATE_IN_API_SUCCEEDED';
export const EDIT_USER_DATE_IN_API_GET_TOKEN_SUCCEEDED =
  'EDIT_USER_DATE_IN_API_GET_TOKEN_SUCCEEDED';
export const EDIT_USER_DATE_IN_API_FAILED = 'EDIT_USER_DATE_IN_API_FAILED';

export const CONNECT_TELEGRAM_IN_API_REQUEST = 'CONNECT_TELEGRAM_IN_API_REQUEST';
export const CONNECT_TELEGRAM_IN_API_SUCCEEDED = 'CONNECT_TELEGRAM_IN_API_SUCCEEDED';
export const CONNECT_TELEGRAM_IN_API_GET_TOKEN_SUCCEEDED =
  'CONNECT_TELEGRAM_IN_API_GET_TOKEN_SUCCEEDED';
export const CONNECT_TELEGRAM_IN_API_FAILED = 'CONNECT_TELEGRAM_IN_API_FAILED';

export const DISCONNECT_TELEGRAM_IN_API_REQUEST = 'DISCONNECT_TELEGRAM_IN_API_REQUEST';
export const DISCONNECT_TELEGRAM_IN_API_SUCCEEDED = 'DISCONNECT_TELEGRAM_IN_API_SUCCEEDED';
export const DISCONNECT_TELEGRAM_IN_API_GET_TOKEN_SUCCEEDED =
  'DISCONNECT_TELEGRAM_IN_API_GET_TOKEN_SUCCEEDED';
export const DISCONNECT_TELEGRAM_IN_API_FAILED = 'DISCONNECT_TELEGRAM_IN_API_FAILED';

export const GET_USER_BY_JWT_IN_API_REQUEST = 'GET_USER_BY_JWT_IN_API_REQUEST';
export const GET_USER_BY_JWT_IN_API_SUCCEEDED = 'GET_USER_BY_JWT_IN_API_SUCCEEDED';
export const GET_USER_BY_JWT_IN_API_GET_TOKEN_SUCCEEDED =
  'GET_USER_BY_JWT_IN_API_GET_TOKEN_SUCCEEDED';
export const GET_USER_BY_JWT_IN_API_FAILED = 'GET_USER_BY_JWT_IN_API_FAILED';

export const GET_ALL_USER_BY_JWT_IN_API_REQUEST = 'GET_ALL_USER_BY_JWT_IN_API_REQUEST';
export const GET_ALL_USER_BY_JWT_IN_API_SUCCEEDED = 'GET_ALL_USER_BY_JWT_IN_API_SUCCEEDED';
export const GET_ALL_USER_BY_JWT_IN_API_GET_TOKEN_SUCCEEDED =
  'GET_ALL_USER_BY_JWT_IN_API_GET_TOKEN_SUCCEEDED';
export const GET_ALL_USER_BY_JWT_IN_API_FAILED = 'GET_ALL_USER_BY_JWT_IN_API_FAILED';

export const SET_ADMIN_STATUS_IN_API_REQUEST = 'SET_ADMIN_STATUS_IN_API_REQUEST';
export const SET_ADMIN_STATUS_IN_API_SUCCEEDED = 'SET_ADMIN_STATUS_IN_API_SUCCEEDED';
export const SET_ADMIN_STATUS_IN_API_GET_TOKEN_SUCCEEDED =
  'SET_ADMIN_STATUS_IN_API_GET_TOKEN_SUCCEEDED';
export const SET_ADMIN_STATUS_IN_API_FAILED = 'SET_ADMIN_STATUS_IN_API_FAILED';

export const ADD_USER_TO_GROUP_IN_API_REQUEST = 'ADD_USER_TO_GROUP_IN_API_REQUEST';
export const ADD_USER_TO_GROUP_IN_API_SUCCEEDED = 'ADD_USER_TO_GROUP_IN_API_SUCCEEDED';
export const ADD_USER_TO_GROUP_IN_API_GET_TOKEN_SUCCEEDED =
  'ADD_USER_TO_GROUP_IN_API_GET_TOKEN_SUCCEEDED';
export const ADD_USER_TO_GROUP_IN_API_FAILED = 'ADD_USER_TO_GROUP_IN_API_FAILED';

export const DELETE_USER_FROM_GROUP_IN_API_REQUEST = 'DELETE_USER_FROM_GROUP_IN_API_REQUEST';
export const DELETE_USER_FROM_GROUP_IN_API_SUCCEEDED = 'DELETE_USER_FROM_GROUP_IN_API_SUCCEEDED';
export const DELETE_USER_FROM_GROUP_IN_API_GET_TOKEN_SUCCEEDED =
  'DELETE_USER_FROM_GROUP_IN_API_GET_TOKEN_SUCCEEDED';
export const DELETE_USER_FROM_GROUP_IN_API_FAILED = 'DELETE_USER_FROM_GROUP_IN_API_FAILED';
