export const LOG_IN_API_REQUEST = 'LOG_IN_API_REQUEST';
export const LOG_IN_API_SUCCEEDED = 'LOG_IN_API_SUCCEEDED';
export const LOG_IN_API_GET_TOKEN_SUCCEEDED = 'LOG_IN_API_GET_TOKEN_SUCCEEDED';
export const LOG_IN_API_FAILED = 'LOG_IN_API_FAILED';

export const LOG_OUT = 'LOG_OUT';

export const OPEN_WINDOW_AUTH = 'OPEN_WINDOW_AUTH';
export const CLOSE_WINDOW_AUTH = 'CLOSE_WINDOW_AUTH';

export const RESET_ERROR = 'RESET_ERROR';

export const EDIT_USER_DATE_IN_API_REQUEST = 'EDIT_USER_DATE_IN_API_REQUEST';
export const EDIT_USER_DATE_IN_API_SUCCEEDED = 'EDIT_USER_DATE_IN_API_SUCCEEDED';
export const EDIT_USER_DATE_IN_API_GET_TOKEN_SUCCEEDED =
  'EDIT_USER_DATE_IN_API_GET_TOKEN_SUCCEEDED';
export const EDIT_USER_DATE_IN_API_FAILED = 'EDIT_USER_DATE_IN_API_FAILED';

export const CONNECT_TELEGRAM_IN_API_REQUEST = 'CONNECT_TELEGRAM_IN_API_REQUEST';
export const CONNECT_TELEGRAM_IN_API_SUCCEEDED = 'CONNECT_TELEGRAM_IN_API_SUCCEEDED';
export const CONNECT_TELEGRAM_IN_API_GET_TOKEN_SUCCEEDED =
  'CONNECT_TELEGRAM_IN_API_GET_TOKEN_SUCCEEDED';
export const CONNECT_TELEGRAM_IN_API_FAILED = 'CONNECT_TELEGRAM_IN_API_FAILED';

export const DISCONNECT_TELEGRAM_IN_API_REQUEST = 'DISCONNECT_TELEGRAM_IN_API_REQUEST';
export const DISCONNECT_TELEGRAM_IN_API_SUCCEEDED = 'DISCONNECT_TELEGRAM_IN_API_SUCCEEDED';
export const DISCONNECT_TELEGRAM_IN_API_GET_TOKEN_SUCCEEDED =
  'DISCONNECT_TELEGRAM_IN_API_GET_TOKEN_SUCCEEDED';
export const DISCONNECT_TELEGRAM_IN_API_FAILED = 'DISCONNECT_TELEGRAM_IN_API_FAILED';
